swagger: '2.0'
info:
  title: 'Marketplace API'
  version: 1.0.0
basePath: /
schemes:
  - http

tags:
  - name: api
  - name: iwc-api

includeRoutes:
    - filePath: api/agency/routes.yml
    - filePath: api/listing/routes.yml


definitions:

  ChangeDetail:
    properties:
      field_name:
        type: string
      id:
        format: int32
        type: integer
      new_value:
        type: string
      old_value:
        type: string
    required:
      - id
      - field_name
      - old_value
      - new_value

  CreateListingProfile:
    properties:
      display_name:
        type: string
      id:
        format: int32
        type: integer
      user:
        $ref: '#/definitions/CreateListingUser'
    required:
      - id
      - user
      - display_name
  CreateListingUser:
    properties:
      id:
        format: int32
        type: integer
      username:
        description: No response was specified
        type: string
    required:
      - id
      - username
  DocUrl:
    properties:
      name:
        type: string
      url:
        type: string
    required:
      - name
      - url
  Group:
    properties:
      name:
        type: string
    required:
      - name
  Image:
    properties:
      id:
        format: int32
        type: integer
      security_marking:
        type: string
      url:
        type: string
    required:
      - url
      - id
      - security_marking
  ImageType:
    properties:
      name:
        $ref: '#/definitions/choice'
        enum:
          - small_icon
          - large_icon
          - banner_icon
          - large_banner_icon
          - small_screenshot
          - large_screenshot
        format: string
    required:
      - name
  Intent:
    properties:
      action:
        type: string
      icon:
        $ref: '#/definitions/ShortImage'
      id:
        format: int32
        type: integer
      label:
        type: string
      media_type:
        type: string
    required:
      - id
      - icon
      - action
      - media_type
      - label
  LibraryListing:
    properties:
      banner_icon:
        $ref: '#/definitions/Image'
      id:
        format: int32
        type: integer
      large_icon:
        $ref: '#/definitions/Image'
      launch_url:
        type: string
      small_icon:
        $ref: '#/definitions/Image'
      title:
        type: string
      unique_name:
        type: string
    required:
      - id
      - title
      - unique_name
      - launch_url
      - small_icon
      - large_icon
      - banner_icon
  Library:
    properties:
      folder:
        type: string
      listing:
        type: string
      owner:
        type: string
      position:
        format: int32
        type: integer
      url:
        type: string
    required:
      - url
      - folder
      - position
      - owner
      - listing
  ListingActivity:
    properties:
      action:
        $ref: '#/definitions/choice'
        enum:
          - CREATED
          - MODIFIED
          - SUBMITTED
          - APPROVED_ORG
          - APPROVED
          - REJECTED
          - ENABLED
          - DISABLED
          - DELETED
          - REVIEW_EDITED
          - REVIEW_DELETED
          - PENDING_DELETION
        format: string
      activity_date:
        format: string
        type: string
      author:
        $ref: '#/definitions/ShortProfile'
      change_details:
        items:
          type: string
        type: array
      description:
        type: string
      listing:
        $ref: '#/definitions/ShortListing'
    required:
      - action
      - activity_date
      - description
      - author
      - listing
      - change_details
  Listing:
    properties:
      tags:
        items:
          type: string
        type: array
      agency:
        $ref: '#/definitions/Agency'
      approval_status:
        $ref: '#/definitions/choice'
        enum:
          - IN_PROGRESS
          - PENDING
          - APPROVED_ORG
          - APPROVED
          - REJECTED
          - DELETED
          - PENDING_DELETION
        format: string
      approved_date:
        format: string
        type: string
      avg_rate:
        format: string
        type: number
      banner_icon:
        $ref: '#/definitions/Image'
      categories:
        items:
          type: string
        type: array
      contacts:
        items:
          type: string
        type: array
      current_rejection:
        $ref: '#/definitions/RejectionListingActivity'
      description:
        type: string
      description_short:
        type: string
      doc_urls:
        items:
          type: string
        type: array
      edited_date:
        format: string
        type: string
      id:
        format: int32
        type: integer
      iframe_compatible:
        type: boolean
      intents:
        items:
          type: string
        type: array
      is_bookmarked:
        type: string
      is_deleted:
        type: boolean
      is_enabled:
        type: boolean
      is_featured:
        type: boolean
      is_private:
        type: boolean
      large_banner_icon:
        $ref: '#/definitions/Image'
      large_icon:
        $ref: '#/definitions/Image'
      last_activity:
        $ref: '#/definitions/ListingActivity'
      launch_url:
        type: string
      listing_type:
        $ref: '#/definitions/ListingType'
      owners:
        items:
          type: string
        type: array
      required_listings:
        $ref: '#/definitions/Nested'
      requirements:
        type: string
      screenshots:
        items:
          type: string
        type: array
      security_marking:
        type: string
      small_icon:
        $ref: '#/definitions/Image'
      title:
        type: string
      total_rate1:
        format: int32
        type: integer
      total_rate2:
        format: int32
        type: integer
      total_rate3:
        format: int32
        type: integer
      total_rate4:
        format: int32
        type: integer
      total_rate5:
        format: int32
        type: integer
      total_review_responses:
        format: int32
        type: integer
      total_reviews:
        format: int32
        type: integer
      total_votes:
        format: int32
        type: integer
      unique_name:
        type: string
      version_name:
        type: string
      what_is_new:
        type: string
    required:
      - id
      - is_bookmarked
      - screenshots
      - doc_urls
      - owners
      - categories
      - tags
      - contacts
      - intents
      - small_icon
      - large_icon
      - banner_icon
      - large_banner_icon
      - agency
      - last_activity
      - current_rejection
      - listing_type
      - title
      - approved_date
      - edited_date
      - description
      - launch_url
      - version_name
      - unique_name
      - what_is_new
      - description_short
      - requirements
      - approval_status
      - is_enabled
      - is_featured
      - is_deleted
      - avg_rate
      - total_votes
      - total_rate5
      - total_rate4
      - total_rate3
      - total_rate2
      - total_rate1
      - total_reviews
      - total_review_responses
      - iframe_compatible
      - security_marking
      - is_private
      - required_listings
  ListingType:
    properties:
      title:
        type: string
    required:
      - title
  Nested:
    properties:
      description:
        type: string
      id:
        format: int32
        type: integer
      title:
        type: string
    required:
      - id
      - title
      - description
  NotificationAgency:
    properties:
      id:
        format: int32
        type: integer
      title:
        type: string
    required:
      - id
      - title
  NotificationListing:
    properties:
      id:
        format: int32
        type: integer
      title:
        type: string
    required:
      - id
      - title
  NotificationMailBox:
    properties:
      acknowledged_status:
        type: boolean
      agency:
        $ref: '#/definitions/NotificationAgency'
      author:
        $ref: '#/definitions/ShortProfile'
      created_date:
        format: string
        type: string
      entity_id:
        format: int32
        type: integer
      expires_date:
        format: string
        type: string
      id:
        format: int32
        type: integer
      listing:
        $ref: '#/definitions/NotificationListing'
      message:
        type: string
      notification_id:
        format: int32
        type: integer
      notification_type:
        type: string
      peer:
        type: string
      read_status:
        type: boolean
    required:
      - id
      - notification_id
      - created_date
      - expires_date
      - author
      - message
      - notification_type
      - listing
      - agency
      - entity_id
      - peer
      - read_status
      - acknowledged_status
  Notification:
    properties:
      agency:
        $ref: '#/definitions/NotificationAgency'
      author:
        $ref: '#/definitions/ShortProfile'
      created_date:
        format: string
        type: string
      entity_id:
        format: int32
        type: integer
      expires_date:
        format: string
        type: string
      id:
        format: int32
        type: integer
      listing:
        $ref: '#/definitions/NotificationListing'
      message:
        type: string
      notification_type:
        $ref: '#/definitions/choice'
        enum:
          - system
          - agency
          - agency_bookmark
          - listing
          - peer
          - peer_bookmark
          - subscription
        format: string
      peer:
        type: string
    required:
      - id
      - created_date
      - expires_date
      - author
      - message
      - notification_type
      - listing
      - agency
      - entity_id
      - peer
  Profile:
    properties:
      bio:
        type: string
      center_tour_flag:
        type: boolean
      display_name:
        type: string
      dn:
        type: string
      email_notification_flag:
        type: boolean
      highest_role:
        type: string
      hud_tour_flag:
        type: boolean
      id:
        format: int32
        type: integer
      is_beta_user:
        type: string
      listing_notification_flag:
        type: boolean
      organizations:
        items:
          type: string
        type: array
      stewarded_organizations:
        items:
          type: string
        type: array
      subscription_notification_flag:
        type: boolean
      user:
        $ref: '#/definitions/User'
      webtop_tour_flag:
        type: boolean
    required:
      - id
      - display_name
      - bio
      - organizations
      - stewarded_organizations
      - user
      - highest_role
      - dn
      - center_tour_flag
      - hud_tour_flag
      - webtop_tour_flag
      - email_notification_flag
      - listing_notification_flag
      - subscription_notification_flag
      - is_beta_user
  RejectionListingActivity:
    properties:
      action:
        $ref: '#/definitions/choice'
        enum:
          - CREATED
          - MODIFIED
          - SUBMITTED
          - APPROVED_ORG
          - APPROVED
          - REJECTED
          - ENABLED
          - DISABLED
          - DELETED
          - REVIEW_EDITED
          - REVIEW_DELETED
          - PENDING_DELETION
        format: string
      activity_date:
        format: string
        type: string
      author:
        $ref: '#/definitions/ShortProfile'
      description:
        type: string
    required:
      - action
      - activity_date
      - description
      - author
  Review:
    properties:
      author:
        $ref: '#/definitions/ShortProfile'
      edited_date:
        format: string
        type: string
      id:
        format: int32
        type: integer
      listing:
        type: string
      rate:
        format: int32
        type: integer
      review_parent:
        type: string
      text:
        type: string
    required:
      - id
      - author
      - listing
      - rate
      - text
      - edited_date
      - review_parent
  Screenshot:
    properties:
      description:
        type: string
      large_image:
        $ref: '#/definitions/Image'
      order:
        format: int32
        type: integer
      small_image:
        $ref: '#/definitions/Image'
    required:
      - order
      - small_image
      - large_image
      - description
  ShortImage:
    properties:
      id:
        format: int32
        type: integer
      security_marking:
        type: string
      url:
        type: string
    required:
      - url
      - id
      - security_marking
  ShortListing:
    properties:
      agency:
        $ref: '#/definitions/Agency'
      id:
        format: int32
        type: integer
      is_deleted:
        type: boolean
      small_icon:
        type: string
      title:
        type: string
      unique_name:
        type: string
    required:
      - unique_name
      - title
      - id
      - agency
      - small_icon
      - is_deleted
  ShortProfile:
    properties:
      display_name:
        type: string
      dn:
        type: string
      id:
        format: int32
        type: integer
      user:
        $ref: '#/definitions/ShortUser'
    required:
      - id
      - user
      - display_name
      - dn
  ShortUser:
    properties:
      email:
        type: string
        format: string
      id:
        format: int32
        type: integer
      username:
        description: No response was specified
        type: string
    required:
      - id
      - username
      - email
  StorefrontListing:
    properties:
      agency:
        $ref: '#/definitions/Agency'
      avg_rate:
        format: string
        type: number
      banner_icon:
        $ref: '#/definitions/Image'
      description_short:
        type: string
      id:
        format: int32
        type: integer
      is_bookmarked:
        type: string
      is_enabled:
        type: boolean
      is_private:
        type: boolean
      large_banner_icon:
        $ref: '#/definitions/Image'
      launch_url:
        type: string
      security_marking:
        type: string
      title:
        type: string
      total_reviews:
        format: int32
        type: integer
      unique_name:
        type: string
    required:
      - id
      - title
      - agency
      - avg_rate
      - total_reviews
      - is_private
      - is_bookmarked
      - description_short
      - security_marking
      - launch_url
      - large_banner_icon
      - banner_icon
      - unique_name
      - is_enabled
  Storefront:
    properties:
      featured:
        items:
          type: string
        type: array
      most_popular:
        items:
          type: string
        type: array
      recent:
        items:
          type: string
        type: array
      recommended:
        items:
          type: string
        type: array
    required:
      - recommended
      - featured
      - recent
      - most_popular
  Subscription:
    properties:
      entity_id:
        format: int32
        type: integer
      entity_type:
        $ref: '#/definitions/choice'
        enum:
          - category
          - tag
        format: string
      id:
        format: int32
        type: integer
      target_profile:
        $ref: '#/definitions/ShortProfile'
    required:
      - id
      - target_profile
      - entity_type
      - entity_id
  Tag:
    properties:
      id:
        format: int32
        type: integer
      name:
        type: string
    required:
      - id
      - name
  UserLibrary:
    properties:
      folder:
        type: string
      id:
        format: int32
        type: integer
      listing:
        $ref: '#/definitions/LibraryListing'
      position:
        format: int32
        type: integer
    required:
      - listing
      - folder
      - id
      - position
  User:
    properties:
      email:
        type: string
        format: string
      groups:
        items:
          type: string
        type: array
      id:
        format: int32
        type: integer
      username:
        description: No response was specified
        type: string
    required:
      - id
      - username
      - email
      - groups
