routes:
- route: /api/listing/
  method: GET
  controller: ../api/listing/listing-controller
  action: listListing

- route: /api/listing/:listing_id
  method: GET
  controller: ../api/listing/listing-controller
  action: retrieve

- route: /api/agency/
  method: GET
  controller: ../api/agency/agency-controller
  action: list

- route: /api/agency/:agency_id
  method: GET
  controller: ../api/agency/agency-controller
  action: retrieve

- route: /api/agency/:agency_id
  method: DELETE
  controller: ../api/agency/agency-controller
  action: destroy

- route: /api/agency/
  method: POST
  controller: ../api/agency/agency-controller
  action: create

- route: /api/profile/
  method: GET
  controller: ../api/profile/profile-controller
  action: list

- route: /api/profile/:profile_id
  method: GET
  controller: ../api/profile/profile-controller
  action: retrieve
